version: "3"

services:

  shopware:
    # use either tag "latest" or any other version like "6.1.5", ...
    image: dockware/dev:latest
    ports:
      - "80:80"
    volumes:
      - "./../plugins:/var/www/html/custom/plugins"
    networks:
      - web
    environment:
      VIRTUAL_HOST: "localhost"
volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
